#!/bin/bash

echo "Adding scores to event-based files..."
echo "2022 RAW"
# python3 Evaluate/ScoresToEventBased.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2022D-v1_RAW_v5.root -t NoSel -d Evaluate/depth_model_v4_LLPanywhere.keras -i Evaluate/inclusive_model_v4_train80.keras -c Evaluate/norm_constants_v4.csv -m filewrite
# python3 Evaluate/ScoresToEventBased.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2022E-v1_RAW_v5.root -t NoSel -d Evaluate/depth_model_v4_LLPanywhere.keras -i Evaluate/inclusive_model_v4_train80.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2022F-v1_RAW_v5.root -t NoSel -d Evaluate/depth_model_v4_LLPanywhere.keras -i Evaluate/inclusive_model_v4_train80.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2022G-v1_RAW_v5.root -t NoSel -d Evaluate/depth_model_v4_LLPanywhere.keras -i Evaluate/inclusive_model_v4_train80.keras -c Evaluate/norm_constants_v4.csv -m filewrite
echo "2023 RAW"
python3 Evaluate/ScoresToEventBased.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2023C-EXOLLPJetHCAL-PromptReco-v1_AOD_v5.root -t NoSel -d Evaluate/depth_model_v4_LLPanywhere.keras -i Evaluate/inclusive_model_v4_train80.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2023C-EXOLLPJetHCAL-PromptReco-v2_AOD_v5.root -t NoSel -d Evaluate/depth_model_v4_LLPanywhere.keras -i Evaluate/inclusive_model_v4_train80.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2023C-EXOLLPJetHCAL-PromptReco-v3_AOD_v5.root -t NoSel -d Evaluate/depth_model_v4_LLPanywhere.keras -i Evaluate/inclusive_model_v4_train80.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2023C-EXOLLPJetHCAL-PromptReco-v4_AOD_v5.root -t NoSel -d Evaluate/depth_model_v4_LLPanywhere.keras -i Evaluate/inclusive_model_v4_train80.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2023D-EXOLLPJetHCAL-PromptReco-v1_AOD_v5.root -t NoSel -d Evaluate/depth_model_v4_LLPanywhere.keras -i Evaluate/inclusive_model_v4_train80.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2023D-EXOLLPJetHCAL-PromptReco-v2_AOD_v5.root -t NoSel -d Evaluate/depth_model_v4_LLPanywhere.keras -i Evaluate/inclusive_model_v4_train80.keras -c Evaluate/norm_constants_v4.csv -m filewrite
echo "LLP MC Signal"
python3 Evaluate/ScoresToEventBased.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/HToSSTo4B_MH125_MS50_CTau3000_v5.root -t NoSel -d Evaluate/depth_model_v4_LLPanywhere.keras -i Evaluate/inclusive_model_v4_train80.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/HToSSTo4B_MH250_MS120_CTau10000_v5.root -t NoSel -d Evaluate/depth_model_v4_LLPanywhere.keras -i Evaluate/inclusive_model_v4_train80.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/HToSSTo4B_MH350_MS160_CTau10000_v5.root -t NoSel -d Evaluate/depth_model_v4_LLPanywhere.keras -i Evaluate/inclusive_model_v4_train80.keras -c Evaluate/norm_constants_v4.csv -m filewrite
# python3 Evaluate/ScoresToEventBased.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/HToSSTo4B_MH350_MS80_CTau500_v5.root -t NoSel -d Evaluate/depth_model_v4_LLPanywhere.keras -i Evaluate/inclusive_model_v4_train80.keras -c Evaluate/norm_constants_v4.csv -m filewrite