#!/bin/bash

echo "Adding scores to event-based files..."
echo "2022 RAW"
python3 Evaluate/ScoresToEventBased_iterate.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2022D-v1_RAW_v5.root -t NoSel -d Evaluate/depth_model_v5.keras -i Evaluate/inclusive_model_v5.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased_iterate.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2022E-v1_RAW_v5.root -t NoSel -d Evaluate/depth_model_v5.keras -i Evaluate/inclusive_model_v5.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased_iterate.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2022F-v1_RAW_v5.root -t NoSel -d Evaluate/depth_model_v5.keras -i Evaluate/inclusive_model_v5.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased_iterate.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2022G-v1_RAW_v5.root -t NoSel -d Evaluate/depth_model_v5.keras -i Evaluate/inclusive_model_v5.keras -c Evaluate/norm_constants_v4.csv -m filewrite
echo "2023 RAW"
python3 Evaluate/ScoresToEventBased_iterate.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2023C-EXOLLPJetHCAL-PromptReco-v1_AOD_v5.root -t NoSel -d Evaluate/depth_model_v5.keras -i Evaluate/inclusive_model_v5.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased_iterate.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2023C-EXOLLPJetHCAL-PromptReco-v2_AOD_v5.root -t NoSel -d Evaluate/depth_model_v5.keras -i Evaluate/inclusive_model_v5.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased_iterate.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2023C-EXOLLPJetHCAL-PromptReco-v3_AOD_v5.root -t NoSel -d Evaluate/depth_model_v5.keras -i Evaluate/inclusive_model_v5.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased_iterate.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2023C-EXOLLPJetHCAL-PromptReco-v4_AOD_v5.root -t NoSel -d Evaluate/depth_model_v5.keras -i Evaluate/inclusive_model_v5.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased_iterate.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2023D-EXOLLPJetHCAL-PromptReco-v1_AOD_v5.root -t NoSel -d Evaluate/depth_model_v5.keras -i Evaluate/inclusive_model_v5.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased_iterate.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.1/DisplacedJet_Run2023D-EXOLLPJetHCAL-PromptReco-v2_AOD_v5.root -t NoSel -d Evaluate/depth_model_v5.keras -i Evaluate/inclusive_model_v5.keras -c Evaluate/norm_constants_v4.csv -m filewrite
echo "LLP MC Signal"
python3 Evaluate/ScoresToEventBased_iterate.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.2/minituple_HToSSTo4B_125_50_CTau3000.root -t NoSel -d Evaluate/depth_model_v5.keras -i Evaluate/inclusive_model_v5.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased_iterate.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.2/minituple_HToSSTo4B_250_120_CTau1000.root -t NoSel -d Evaluate/depth_model_v5.keras -i Evaluate/inclusive_model_v5.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased_iterate.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.2/minituple_HToSSTo4B_350_MS160_CTau10000.root -t NoSel -d Evaluate/depth_model_v5.keras -i Evaluate/inclusive_model_v5.keras -c Evaluate/norm_constants_v4.csv -m filewrite
python3 Evaluate/ScoresToEventBased_iterate.py -f /eos/cms/store/group/phys_exotica/HCAL_LLP/MiniTuples/v5.2/minituple_HToSSTo4B_350_80_CTau500.root -t NoSel -d Evaluate/depth_model_v5.keras -i Evaluate/inclusive_model_v5.keras -c Evaluate/norm_constants_v4.csv -m filewrite